# Generated by Django 3.0.7 on 2020-07-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_f', models.CharField(max_length=15)),
                ('contact_f', models.IntegerField()),
                ('email_f', models.TextField()),
                ('comment_f', models.CharField(max_length=200)),
            ],
        ),
    ]
